services:
  nextjs:
    build: ./client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    
  api:
    build: ./server/api
    ports:
      - '8000:8000'
    volumes:
      - ./server/api:/app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./server/.env.prod
    depends_on:
      - db
  
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./server/.env.prod

volumes:
  postgres_data: