# Generated by Django 5.1.3 on 2024-11-16 12:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField(verbose_name='Region Code')),
                ('name', models.CharField(max_length=50)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Subregion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subregion', models.IntegerField(verbose_name='Subregion Code')),
                ('name', models.CharField(max_length=50)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie', models.CharField(choices=[('FD', 'Fallow deer'), ('RedD', 'Red deer'), ('RoeD', 'Roe deer'), ('WB', 'Wild boar'), ('SH', 'Scottish Highlander'), ('W', 'Wolf')], default='FD', max_length=4)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='M', max_length=1)),
                ('age', models.CharField(choices=[('A', 'Adult'), ('M', 'Mature'), ('Y', 'Young'), ('U', 'Unknown')], default='A', max_length=1)),
                ('health', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('U', 'Unknown')], default='1', max_length=1)),
                ('observe_count', models.IntegerField()),
                ('date', models.DateField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('desc', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subregion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.subregion')),
            ],
        ),
    ]
