# Generated by Django 5.1.3 on 2024-11-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='observation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
